sudo: false

language: java

jdk: oraclejdk8

notifications:
  irc: "chat.freenode.net#seedstack-dev"

cache:
  directories:
    - "$HOME/.m2/repository"

install: mvn -q install

script: if [ $TRAVIS_PULL_REQUEST = false ] && [ $TRAVIS_BRANCH = master ]; then mvn -q deploy; fi
