sudo: false

language: java

jdk: oraclejdk8

notifications:
  irc: "chat.freenode.net#seedstack-dev"

cache:
  directories:
    - "$HOME/.m2/repository"

install: /bin/true

script: mvn -q -B -T 2 install

after_success: if [ $TRAVIS_PULL_REQUEST = false ] && [ $TRAVIS_BRANCH = master ]; then mvn -q deploy; fi
